version: '3'
services:
  db:
    build: .
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - "5432"
