version: "3"

volumes:
  postgis13_data:

services:

  db:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5434:5434
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres2
    volumes:
      - postgis13_data:/var/lib/postgresql/data/
